name: ビルド

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: 3.18.1

      - run: |
          chmod +x ./gradlew
          ./gradlew :module:assembleRelease --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: zygisk-imguimenu
          path: out/magisk_module_release/
